### ISSUE TITLE
Unable to set preferred logout binding

### ISSUE THREAD

**Issue by agxs** [IdentityPython/pysaml2#802]
I'm working with an IdP/federation that only supports the REDIRECT logout binding and not the POST logout binding and I'm having trouble forcing pysaml2 to not use the POST binding. I'm using pysaml2 in Django and using djangosaml2 as well.

I'm setting the preferred binding in the following way and this appears to not be applying:

```
        'preferred_binding': {
            "single_logout_service": [
                saml2.BINDING_HTTP_REDIRECT,
            ],
        },
```

I've verified that at runtime the `config.preferred_binding` dict contains my overridden value.

## Code Version

v6.5.1

## Expected Behavior

I'm trying to force the `urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect` to be used but `urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST` is being used.

## Current Behavior

I believe that when setting the preferred binding as described in https://pysaml2.readthedocs.io/en/latest/howto/config.html#preferred-binding should force that binding no matter what.

## Possible Solution

The issue appears to be with this section of code in `client.py` at line 633:

```
        if binding == BINDING_SOAP:
            response_bindings = [BINDING_SOAP]
        elif binding in [BINDING_HTTP_POST, BINDING_HTTP_REDIRECT]:
            response_bindings = [BINDING_HTTP_POST, BINDING_HTTP_REDIRECT]
        else:
            response_bindings = self.config.preferred_binding["single_logout_service"]
```

When setting breakpoints, my `binding` variable is set to `urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect` however due to the above ordering of the if/elses the `response_bindings` is set to `[BINDING_HTTP_POST, BINDING_HTTP_REDIRECT]`.

This appears to cause the POST binding to be used, `rinfo["binding"]` at the end of the `handle_logout_request` is set to `urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST`.

Should the else that checks for the `preferred_binding` not be the first thing that's checked so that the preferred binding can be set?

## Steps to Reproduce

1. Setup an SP and set the logout referred binding to redirect
2. Call the logout service on the SP
3. See that the POST binding is used even though REDIRECT is requested

**Comment by c00kiemon5ter** [comment]
hello, from what you write you are controlling an SP. I don't think `handle_logout_request` is what you should be looking into. Did you get to it by following the code?

I think 71b53cf should fix this issue. If possible, please, test this and let me know.

**Comment by agxs** [comment]
I found `handle_logout_request` by tracing through the code with breakpoints. It's definitely hit when a logout from the from the IdP is triggered.

The code in https://github.com/IdentityPython/pysaml2/commit/71b53cf466207a78b1369cde3072bdf1a8897d49 doesn't seem to fix the problem. In fact, it's not even hit by a breakpoint when I test it.

**Comment by agxs** [comment]
Just for a bit more clarity, yes I'm controlling the SP.

The `handle_logout_request` method is correctly called with `binding='urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'`, (which changes depending on how I set up my config, in my case I'm only declaring the REDIRECT binding in the `single_logout_service` config).

However when `self.create_logout_response` is called from this method on line 650, `response_bindings` has been set to `response_bindings = [BINDING_HTTP_POST, BINDING_HTTP_REDIRECT]` on the line up in my original post. They the rest of the code picks the POST binding because it is first in this list.

Additionally the code in `entity.py` `pick_binding` is checking the preferred binding last too so never gets chose, as Binding is never `None` for me:

```
        if bindings is None:
            if request and request.protocol_binding:
                bindings = [request.protocol_binding]
            else:
                bindings = self.config.preferred_binding[service]
```

I hope that all makes sense.

**Comment by c00kiemon5ter** [comment]
OK, I now understand that it is the IdP that is initiating the logout - not the SP. I will look into this.

**Comment by c00kiemon5ter** [comment]
Hello again, please check latest master (1548443...d4cc248).
The order is now preserved based on the requested binding.

> I believe that when setting the preferred binding as described in https://pysaml2.readthedocs.io/en/latest/howto/config.html#preferred-binding should force that binding no matter what.

I don't think this is correct. The argument should always have precedence. If no argument is defined (its value is `None`) then we fall back to the configuration. Explicitness always takes precedence. The argument is explicit, while the configuration is implicit.

**Comment by agxs** [comment]
This fixed the problem for us, thanks!

**Comment by c00kiemon5ter** [comment]
Thank you for testing. I will put out a new release with this fix.
